### ISSUE TITLE
| Greyhounds Review | - 2/04/2020 

### ISSUE THREAD

**Issue by HeflerDev** [aecordova/Capstone-Ruby-Linter#3]
Hey **Angel**,  how things going ?
Your project seen's awesome, it's well indented and the the code is very clear.
--------------------------------------------------------------------------------------------------------------
-[ ] The only thing we suggest you to do is to test your code using RSpec, so It helps you find out hidden issues and help collaborators to use your code.

That's it, we wish you happy coding !

<img  src='https://img.devrant.com/devrant/rant/r_565529_WRQcK.jpg'>

**Comment by aecordova** [comment]
Hi! Thanks! I just added the rSpect tests
